### ISSUE TITLE
cds: not found error when deploying service to production

### ISSUE THREAD

**Issue by MartinStenzig** [chgeo/cds-swagger-ui-express#8] opened 2021-10-14 20:56 UTC
I kept the server.js to a minimum and in line with the documentation. If I only add the cds-swagger-ui-express package to the development dependencies, I receive the error shown below in a production deployment. 

Changing the package to a "full" dependency fixes the problem, so I would suggest at least changing the documentation to reflect that. 

**server.js**
```javascript
const cds = require('@sap/cds')
module.exports = cds.server

console.log('MST Environment Type: ' + process.env.NODE_ENV)
if (process.env.NODE_ENV !== 'production') {
  const cds_swagger = require('cds-swagger-ui-express')
  cds.on('bootstrap', app => app.use(cds_swagger()))
}
```

**service log file**
```

 2021-10-14T13:51:01.61-0700 [STG/0] OUT Uploading droplet, build artifacts cache...
   2021-10-14T13:51:01.61-0700 [STG/0] OUT Uploading droplet...
   2021-10-14T13:51:01.62-0700 [STG/0] OUT Uploading build artifacts cache...
   2021-10-14T13:51:01.66-0700 [STG/0] OUT Uploaded build artifacts cache (225B)
   2021-10-14T13:51:02.92-0700 [API/52] OUT Creating droplet for app with guid e43383fa-61f5-476c-bdd7-61a11c24ac5d
   2021-10-14T13:51:06.15-0700 [STG/0] OUT Uploaded droplet (86.3M)
   2021-10-14T13:51:06.16-0700 [STG/0] OUT Uploading complete
   2021-10-14T13:51:06.30-0700 [STG/0] OUT Cell f5a8de1f-45ae-42d0-b8d2-bad0f239865b stopping instance 7af596e1-f9a9-42b8-895d-6a222fc8925b
   2021-10-14T13:51:06.30-0700 [STG/0] OUT Cell f5a8de1f-45ae-42d0-b8d2-bad0f239865b destroying container for instance 7af596e1-f9a9-42b8-895d-6a222fc8925b
   2021-10-14T13:51:07.06-0700 [STG/0] OUT Cell f5a8de1f-45ae-42d0-b8d2-bad0f239865b successfully destroyed container for instance 7af596e1-f9a9-42b8-895d-6a222fc8925b
   2021-10-14T13:51:13.68-0700 [API/1] OUT Updated app with guid e43383fa-61f5-476c-bdd7-61a11c24ac5d ({:droplet_guid=>"ca6a041c-c803-4825-882d-9853ce893098"})
   2021-10-14T13:51:14.40-0700 [API/44] OUT Creating revision for app with guid e43383fa-61f5-476c-bdd7-61a11c24ac5d
   2021-10-14T13:51:14.48-0700 [API/44] OUT Starting app with guid e43383fa-61f5-476c-bdd7-61a11c24ac5d
   2021-10-14T13:51:14.73-0700 [CELL/0] OUT Cell 2df9ad23-26f8-49d7-b4f5-70cbf2810414 creating container for instance 8a7e4f82-08a5-4561-618a-f438
   2021-10-14T13:51:15.06-0700 [CELL/0] OUT Cell 2df9ad23-26f8-49d7-b4f5-70cbf2810414 successfully created container for instance 8a7e4f82-08a5-4561-618a-f438
   2021-10-14T13:51:15.20-0700 [CELL/0] OUT Downloading droplet...
   2021-10-14T13:51:19.12-0700 [CELL/0] OUT Downloaded droplet (86.3M)
   2021-10-14T13:51:19.12-0700 [CELL/0] OUT Starting health monitoring of container
   2021-10-14T13:51:19.80-0700 [APP/PROC/WEB/0] OUT > sf-hana-loader@1.0.0 start
   2021-10-14T13:51:19.80-0700 [APP/PROC/WEB/0] OUT > cds run
   2021-10-14T13:51:19.81-0700 [APP/PROC/WEB/0] ERR sh: 1: cds: not found
   2021-10-14T13:51:19.81-0700 [APP/PROC/WEB/0] ERR npm notice
   2021-10-14T13:51:19.81-0700 [APP/PROC/WEB/0] ERR npm notice New major version of npm available! 7.13.0 -> 8.0.0
   2021-10-14T13:51:19.81-0700 [APP/PROC/WEB/0] ERR npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.0.0>
   2021-10-14T13:51:19.81-0700 [APP/PROC/WEB/0] ERR npm notice Run `npm install -g npm@8.0.0` to update!
   2021-10-14T13:51:19.81-0700 [APP/PROC/WEB/0] ERR npm notice
   2021-10-14T13:51:19.82-0700 [APP/PROC/WEB/0] OUT Exit status 127
```

**Comment by chgeo** [comment] 2022-03-11 12:56
Closing thus, assuming it's no longer an issue

**Closed** 2022-03-11 12:57 UTC

**Comment by muellerj93** [comment] 2023-02-24 16:09
Hi @chgeo,

I can confirm the behaviour that @MartinStenzig posted in this issue.

Additionally I can provide some more details as to what the effects are when this dependency is set only as dev dependency for an app that is pushed to prod.

**Root cause:**
If `cds-swagger-ui-express` is set as devDependency, it causes `npm install --omit=dev` (npm install --production) to forget to create a symlink in the `node_modules/.bin` directory to the `@sap/cds` cli binary.
That causes the exact same error message as Martin reported.

<details>
<summary>In depth analysis (in case it's useful):</summary>
As at least I learned a lot about node / npm / cf deployments while analyzing this issue, I thought it'd make sense to share how I analyzed the issue here.

At first I tried to verify what my deployed artifact looked like so I downloaded the artifact with the `cf download-droplet` command and checked if everything was in place and as I expected it to look like (at this point I didn't know the node_modules/.bin directory, which couldve saved me a lot of time :D).

As I didn't find anything suspicious there, I went with the approach of providing a dummy entrypoint (namely a dummy server to have a healthy container) to be able to ssh into the deployed container.

I looked around a bit, checked the npm config and didn't find anything suspicious.
I googled a bit and found the some useful npm commands:
- `npm root` (Print the effective node_modules folder to standard out.)
- `npm bin` (Print the folder where npm will install executables)

The second one sounded interesting and that's how I found the `node_modules/.bin` directory.
I checked it out and found, that it contains symlinks to the binaries of installed packages (in case they provide the "bin" property in package.json).
Only the `cds` binary was not listed there.

After that I tried reproducing the issue locally by `npm install --omit=dev` and then it was also missing locally.
Checking my version history of what I'd done was the last step to find out what might've caused the issue and here I am writing this explanation.
</details>

**Solution:**
To solve the issue I did the same thing as Martin and moved the dependency to prod dependencies.
So I guess either the documentation should be adjusted or someone should look into why the above happens, as it's **totally unexpected** and some **very strange side-effect** (at least for me).

Best regards

**Comment by chgeo** [comment] 2023-03-01 15:53
Yes, we are aware of the issue, which ultimately is caused by the double `cds` executable in both `@sap/cds` and `@sap/cds-dk`.  This is historically grown, and npm does not seem to like it.

At the moment, we are considering options to rename one of them.  As this can only be done in a major version, the issue will still take some time to resolve (maybe we need two major versions).

In the meantime I will add a hint to the docs.
Thanks.
